### ISSUE TITLE
`react-oidc-context` does not permit the `http` scheme 

### ISSUE THREAD

**Issue by aryanpingle** [INTO-CPS-Association/DTaaS#899] opened 2024-09-05 06:33 UTC
As of now, DTaaS uses `https://gitlab.com` as an OAuth provider, which works with no problems.

With the ongoing effort to switch to an integrated GitLab instance (#892), if a DTaaS server is set up at `http://site.com` (note: http and not https) the local gitlab instance would be available at `http://site.com/gitlab`. However, the homepage "sign in with GitLab" button redirects to `https://site.com/gitlab` because of a [known issue with `oidc-client-ts`](https://github.com/authts/react-oidc-context/issues/1288) that automatically uses `https`.

This might even break development servers at `http://localhost` for the same reason - I'll try it out and post it here.

**Comment by aryanpingle** [comment] 2024-09-05 06:43
Worth noting: Having OAuth on http kind of breaks the purpose of having authentication in the first place, as network requests aren't encrypted anymore. The most likely use case for this would be when you're setting up a DTaaS server and you haven't enabled TLS for your domain yet. Perhaps we could offer a setup option for the server to use `gitlab.com` instead of the path prefixed local instance?

**Comment by prasadtalasila** [comment] 2024-09-19 11:54
The PR #905 adds support for https://foo.com/gitlab. Let us have a similar setup for https://localhost/gitlab and close the issue.

**Comment by prasadtalasila** [comment] 2024-10-08 15:15
The problem is beyond the purview of this project. An explanation has been added in PR #961

**Closed by prasadtalasila** 2024-10-08 15:15 UTC
